### ISSUE TITLE
Filter with no arguments cause trouble in Groups

### ISSUE THREAD

**Issue by thomgb** [loicsander/Robofont-scripts#10]
Hi!

title says it all :)

here is my report: 
```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "penBallWizard.py", line 412, in processFilterGroup
  File "penBallWizard.py", line 412, in <dictcomp>
KeyError: 'arguments'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 157, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "penBallWizard.py", line 412, in processFilterGroup
  File "penBallWizard.py", line 412, in <dictcomp>
KeyError: 'arguments'
```

Hope it helps.

Best, 
Thom

**Comment by loicsander** [comment]
Thanks for the report, I’ll look into that!

**Comment by loicsander** [comment]
Last commit should solve the issue. Let me know if it’s fixed on your side.

**Comment by thomgb** [comment]
Yes! This solved! 
Thanks, Loic
