### ISSUE TITLE
from cleanPen import FilterPointPen / cannot import name FilterPointPen

### ISSUE THREAD

**Issue by thomgb** [loicsander/Robofont-scripts#15]
I suspect that you didnt commit cleanPen.py :)

```
Traceback (most recent call last):
  File "penBallWizard.py", line 14, in <module>
  File "/Users/thomjanssen/Library/Application Support/RoboFont/plugins/PenBallWizard.roboFontExt/lib/objects/manager.py", line 11, in <module>
  File "/Users/thomjanssen/Library/Application Support/RoboFont/plugins/PenBallWizard.roboFontExt/lib/objects/glyphFilter.py", line 9, in <module>
ImportError: cannot import name FilterPointPen
```

**Comment by loicsander** [comment]
Worse, I changed it, I’m revising the inner workings in hopes of reaching a first stable version, thanks for standing by and being such a patient tester ; )

Last commit should bring things back to normal.

**Comment by thomgb** [comment]
Hey man its my pleasure. Glad to help. 
And I think I speak for many to say thank you for making these tools. :) Thumbs up!

This issue is solved.
