### ISSUE TITLE
Extension won't initiate in RF3

### ISSUE THREAD

**Issue by sponcey** [loicsander/Robofont-scripts#31]
Is ScaleFast currently supported in RF3? I tried initializing ScaleFast after a fresh install, and I get this error in the output:

`Traceback (most recent call last):
​  File "scaleFast.py", line 1532, in <module>
  File "scaleFast.py", line 387, in __init__
  File "scaleFast.py", line 920, in _selectedFontChanged
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 59, in getRefStems
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 127, in freezeGlyph
  File "/Users/Cadmon/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 177, in extractComposites
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/deprecated.py", line 77, in transform
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/base.py", line 466, in transformBy
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/normalizers.py", line 999, in normalizeTransformationMatrix
TypeError: Transformation matrices must be tuple instances, not Transform.
`

**Comment by gferreira** [comment]
ScaleFast and the other extensions in this repository are now maintained by [RoboDocs](https://github.com/robodocs/).

the updated version of ScaleFast is [here](https://github.com/robodocs/scalefast). or get it with [Mechanic2](https://robofontmechanic.com)
